BEGIN;
WITH incoming("id","name","description","sortOrder") AS (VALUES ('menu-cat-cafe','Café da Manhã','Pães, bebidas e opções para começar o dia.',10),
('menu-cat-dia','Prato do Dia','Pratos caseiros programados por dia da semana.',20),
('menu-cat-pratos','Pratos','Pratos completos do Restaurante Moriah.',30),
('menu-cat-porcoes','Porções','Porções, pastéis, fritas e caldos.',40),
('menu-cat-pan-s','Panquecas Salgadas','Panquecas salgadas e opções vegetarianas.',50),
('menu-cat-pan-d','Panquecas Doces','Panquecas doces.',60))
UPDATE "RestaurantCategory" c SET "description"=i."description","sortOrder"=i."sortOrder","active"=true FROM incoming i WHERE lower(c."name")=lower(i."name");
WITH incoming("id","name","description","sortOrder") AS (VALUES ('menu-cat-cafe','Café da Manhã','Pães, bebidas e opções para começar o dia.',10),
('menu-cat-dia','Prato do Dia','Pratos caseiros programados por dia da semana.',20),
('menu-cat-pratos','Pratos','Pratos completos do Restaurante Moriah.',30),
('menu-cat-porcoes','Porções','Porções, pastéis, fritas e caldos.',40),
('menu-cat-pan-s','Panquecas Salgadas','Panquecas salgadas e opções vegetarianas.',50),
('menu-cat-pan-d','Panquecas Doces','Panquecas doces.',60))
INSERT INTO "RestaurantCategory" ("id","name","description","sortOrder","active","featured")
SELECT i."id",i."name",i."description",i."sortOrder",true,false FROM incoming i
WHERE NOT EXISTS(SELECT 1 FROM "RestaurantCategory" c WHERE lower(c."name")=lower(i."name"));

WITH incoming("id","sku","categoryName","name","description","priceCents","availableDays","sortOrder") AS (VALUES ('menu-caf-001','MENU-CAF-001','Café da Manhã','Pão com manteiga','Pão servido com manteiga.',700,ARRAY[]::INTEGER[],10),
('menu-caf-002','MENU-CAF-002','Café da Manhã','Pão na chapa','Pão preparado na chapa.',900,ARRAY[]::INTEGER[],20),
('menu-caf-003','MENU-CAF-003','Café da Manhã','Misto frio','Sanduíche misto servido frio.',1100,ARRAY[]::INTEGER[],30),
('menu-caf-004','MENU-CAF-004','Café da Manhã','Misto quente','Sanduíche misto preparado quente.',1200,ARRAY[]::INTEGER[],40),
('menu-caf-005','MENU-CAF-005','Café da Manhã','Ovos mexidos','Porção de ovos mexidos.',1300,ARRAY[]::INTEGER[],50),
('menu-caf-006','MENU-CAF-006','Café da Manhã','Tapioca','Escolha o recheio: carne seca, manteiga do Nordeste ou ovos mexidos.',1500,ARRAY[]::INTEGER[],60),
('menu-caf-007','MENU-CAF-007','Café da Manhã','Suco natural 500 ml','Suco natural 500 ml. Escolha o sabor.',1000,ARRAY[]::INTEGER[],70),
('menu-caf-008','MENU-CAF-008','Café da Manhã','Vitamina 500 ml','Vitamina 500 ml. Escolha o sabor.',1700,ARRAY[]::INTEGER[],80),
('menu-caf-009','MENU-CAF-009','Café da Manhã','Café Moriah torrado','Café Moriah torrado.',700,ARRAY[]::INTEGER[],90),
('menu-caf-010','MENU-CAF-010','Café da Manhã','Achocolatado','Achocolatado.',900,ARRAY[]::INTEGER[],100),
('menu-caf-011','MENU-CAF-011','Café da Manhã','Leite','Leite.',500,ARRAY[]::INTEGER[],110),
('menu-caf-012','MENU-CAF-012','Café da Manhã','Capuchino Moriah','Capuchino Moriah.',1000,ARRAY[]::INTEGER[],120),
('menu-dia-001','MENU-DIA-001','Prato do Dia','Carne de panela','Prato do dia de segunda-feira. Acompanha farofa, arroz, feijão, salada e refrigerante 269 ml.',3200,ARRAY[1]::INTEGER[],10),
('menu-dia-002','MENU-DIA-002','Prato do Dia','Virado à paulista','Prato do dia de terça-feira. Acompanha farofa, arroz, feijão, salada e refrigerante 269 ml.',2800,ARRAY[2]::INTEGER[],20),
('menu-dia-003','MENU-DIA-003','Prato do Dia','Feijoada','Prato do dia de quarta-feira. Acompanha farofa, arroz, feijão, salada e refrigerante 269 ml.',3500,ARRAY[3]::INTEGER[],30),
('menu-dia-004','MENU-DIA-004','Prato do Dia','Parmegiana de carne','Prato do dia de quinta-feira. Acompanha farofa, arroz, feijão, salada e refrigerante 269 ml.',3800,ARRAY[4]::INTEGER[],40),
('menu-dia-005','MENU-DIA-005','Prato do Dia','Costelinha suína','Prato do dia de sexta-feira. Acompanha farofa, arroz, feijão, salada e refrigerante 269 ml.',3300,ARRAY[5]::INTEGER[],50),
('menu-dia-006','MENU-DIA-006','Prato do Dia','Moqueca de peixe','Prato do dia de sábado. Acompanha farofa, arroz, feijão, salada e refrigerante 269 ml.',3500,ARRAY[6]::INTEGER[],60),
('menu-dia-007','MENU-DIA-007','Prato do Dia','Churrasco','Prato do dia de domingo. Acompanha farofa, arroz, feijão, salada e refrigerante 269 ml.',3400,ARRAY[0]::INTEGER[],70),
('menu-pra-001','MENU-PRA-001','Pratos','Calabresa acebolada','Acompanha farofa, arroz, feijão, salada e refrigerante 269 ml.',2800,ARRAY[]::INTEGER[],10),
('menu-pra-002','MENU-PRA-002','Pratos','Bife acebolado','Acompanha farofa, arroz, feijão, salada e refrigerante 269 ml.',3200,ARRAY[]::INTEGER[],20),
('menu-pra-003','MENU-PRA-003','Pratos','Omelete recheado','Acompanha farofa, arroz, feijão, salada e refrigerante 269 ml.',2300,ARRAY[]::INTEGER[],30),
('menu-pra-004','MENU-PRA-004','Pratos','Frango grelhado com fritas','Acompanha farofa, arroz, feijão, salada e refrigerante 269 ml.',2500,ARRAY[]::INTEGER[],40),
('menu-pra-005','MENU-PRA-005','Pratos','Frango a passarinho','Acompanha farofa, arroz, feijão, salada e refrigerante 269 ml.',2800,ARRAY[]::INTEGER[],50),
('menu-pra-006','MENU-PRA-006','Pratos','Filé de peixe à milanesa','Acompanha farofa, arroz, feijão, salada e refrigerante 269 ml.',3200,ARRAY[]::INTEGER[],60),
('menu-pra-007','MENU-PRA-007','Pratos','Macarronada à bolonhesa','Acompanha farofa, arroz, feijão, salada e refrigerante 269 ml.',2800,ARRAY[]::INTEGER[],70),
('menu-pra-008','MENU-PRA-008','Pratos','Panqueca (serve 2 pessoas)','Panqueca para duas pessoas com carne, queijo, frango e catupiry. Adicionais disponíveis.',5200,ARRAY[]::INTEGER[],80),
('menu-pra-009','MENU-PRA-009','Pratos','Prato kids com fritas','Escolha entre calabresa, iscas de carne, carne moída ou nuggets. Acompanha refrigerante 269 ml e sobremesa.',2200,ARRAY[]::INTEGER[],90),
('menu-por-001','MENU-POR-001','Porções','Isca de frango','Porção de iscas de frango.',3800,ARRAY[]::INTEGER[],10),
('menu-por-002','MENU-POR-002','Porções','Contra-filé acebolado','Porção de contra-filé acebolado.',4200,ARRAY[]::INTEGER[],20),
('menu-por-003','MENU-POR-003','Porções','Tilápia com anéis de cebola','Porção de tilápia com anéis de cebola.',4500,ARRAY[]::INTEGER[],30),
('menu-por-004','MENU-POR-004','Porções','Anéis de cebola e cebola crispy','Porção de anéis de cebola e cebola crispy.',3800,ARRAY[]::INTEGER[],40),
('menu-por-005','MENU-POR-005','Porções','Fritas recheadas','Porção de fritas recheadas.',3500,ARRAY[]::INTEGER[],50),
('menu-por-006','MENU-POR-006','Porções','Fritas simples','Porção de fritas simples.',2800,ARRAY[]::INTEGER[],60),
('menu-por-007','MENU-POR-007','Porções','Pastel','Escolha o recheio: frango com catupiry, 3 queijos, queijo, carne, palmito ou alho.',1400,ARRAY[]::INTEGER[],70),
('menu-por-008','MENU-POR-008','Porções','Pastel Big Monster Especial','Pastel especial com todos os recheios.',2200,ARRAY[]::INTEGER[],80),
('menu-por-009','MENU-POR-009','Porções','6 mini pastéis','Seis mini pastéis nos sabores carne, queijo e frango.',2400,ARRAY[]::INTEGER[],90),
('menu-por-010','MENU-POR-010','Porções','Caldos','Escolha o sabor: calabresa, frango, carne, caldo verde, caldo de moqueca ou legumes.',2600,ARRAY[]::INTEGER[],100),
('menu-pan-s-001','MENU-PAN-S-001','Panquecas Salgadas','Panqueca de frango','Panqueca salgada de frango.',2400,ARRAY[]::INTEGER[],10),
('menu-pan-s-002','MENU-PAN-S-002','Panquecas Salgadas','Panqueca de carne','Panqueca salgada de carne.',2400,ARRAY[]::INTEGER[],20),
('menu-pan-s-003','MENU-PAN-S-003','Panquecas Salgadas','Panqueca de calabresa','Panqueca salgada de calabresa.',2400,ARRAY[]::INTEGER[],30),
('menu-pan-s-004','MENU-PAN-S-004','Panquecas Salgadas','Panqueca de presunto e queijo','Panqueca salgada de presunto e queijo.',2300,ARRAY[]::INTEGER[],40),
('menu-pan-s-005','MENU-PAN-S-005','Panquecas Salgadas','Panqueca de toscana com bacon','Panqueca salgada de toscana com bacon.',2500,ARRAY[]::INTEGER[],50),
('menu-pan-s-006','MENU-PAN-S-006','Panquecas Salgadas','Panqueca de costelinha','Panqueca salgada de costelinha.',2700,ARRAY[]::INTEGER[],60),
('menu-pan-s-007','MENU-PAN-S-007','Panquecas Salgadas','Panqueca vegetariana','Opções vegetarianas: milho, espinafre, escarola, brócolis ou alho frito.',2200,ARRAY[]::INTEGER[],70),
('menu-pan-d-001','MENU-PAN-D-001','Panquecas Doces','Panqueca de doce de leite','Panqueca doce de doce de leite.',1800,ARRAY[]::INTEGER[],10),
('menu-pan-d-002','MENU-PAN-D-002','Panquecas Doces','Panqueca de brigadeiro','Panqueca doce de brigadeiro.',1800,ARRAY[]::INTEGER[],20),
('menu-pan-d-003','MENU-PAN-D-003','Panquecas Doces','Panqueca de Nutella','Panqueca doce de Nutella.',1800,ARRAY[]::INTEGER[],30),
('menu-pan-d-004','MENU-PAN-D-004','Panquecas Doces','Panqueca de beijinho','Panqueca doce de beijinho.',1800,ARRAY[]::INTEGER[],40),
('menu-pan-d-005','MENU-PAN-D-005','Panquecas Doces','Panqueca de Sonho de Valsa','Panqueca doce de Sonho de Valsa.',1900,ARRAY[]::INTEGER[],50),
('menu-pan-d-006','MENU-PAN-D-006','Panquecas Doces','Panqueca de morango com leite condensado','Panqueca doce de morango com leite condensado.',2000,ARRAY[]::INTEGER[],60),
('menu-pan-d-007','MENU-PAN-D-007','Panquecas Doces','Panqueca de abacaxi com chocolate','Panqueca doce de abacaxi com chocolate.',2000,ARRAY[]::INTEGER[],70),
('menu-pan-d-008','MENU-PAN-D-008','Panquecas Doces','Panqueca de banana com canela','Panqueca doce de banana com canela.',1800,ARRAY[]::INTEGER[],80)),
resolved AS (
 SELECT i.*,c."id" AS "categoryId" FROM incoming i
 JOIN LATERAL (SELECT c0."id" FROM "RestaurantCategory" c0 WHERE lower(c0."name")=lower(i."categoryName") ORDER BY CASE WHEN c0."id" LIKE 'menu-cat-%' THEN 0 ELSE 1 END,c0."sortOrder",c0."id" LIMIT 1)c ON true
)
UPDATE "RestaurantProduct" p SET
 "categoryId"=r."categoryId","name"=r."name","description"=r."description","priceCents"=r."priceCents",
 "active"=true,"soldOut"=false,"sortOrder"=r."sortOrder","availableDays"=r."availableDays","trackStock"=false,"updatedAt"=CURRENT_TIMESTAMP,
 "sku"=CASE WHEN p."sku" IS NULL AND NOT EXISTS(SELECT 1 FROM "RestaurantProduct" p2 WHERE p2."sku"=r."sku" AND p2."id"<>p."id") THEN r."sku" ELSE p."sku" END
FROM resolved r WHERE p."sku"=r."sku" OR lower(p."name")=lower(r."name");

WITH incoming("id","sku","categoryName","name","description","priceCents","availableDays","sortOrder") AS (VALUES ('menu-caf-001','MENU-CAF-001','Café da Manhã','Pão com manteiga','Pão servido com manteiga.',700,ARRAY[]::INTEGER[],10),
('menu-caf-002','MENU-CAF-002','Café da Manhã','Pão na chapa','Pão preparado na chapa.',900,ARRAY[]::INTEGER[],20),
('menu-caf-003','MENU-CAF-003','Café da Manhã','Misto frio','Sanduíche misto servido frio.',1100,ARRAY[]::INTEGER[],30),
('menu-caf-004','MENU-CAF-004','Café da Manhã','Misto quente','Sanduíche misto preparado quente.',1200,ARRAY[]::INTEGER[],40),
('menu-caf-005','MENU-CAF-005','Café da Manhã','Ovos mexidos','Porção de ovos mexidos.',1300,ARRAY[]::INTEGER[],50),
('menu-caf-006','MENU-CAF-006','Café da Manhã','Tapioca','Escolha o recheio: carne seca, manteiga do Nordeste ou ovos mexidos.',1500,ARRAY[]::INTEGER[],60),
('menu-caf-007','MENU-CAF-007','Café da Manhã','Suco natural 500 ml','Suco natural 500 ml. Escolha o sabor.',1000,ARRAY[]::INTEGER[],70),
('menu-caf-008','MENU-CAF-008','Café da Manhã','Vitamina 500 ml','Vitamina 500 ml. Escolha o sabor.',1700,ARRAY[]::INTEGER[],80),
('menu-caf-009','MENU-CAF-009','Café da Manhã','Café Moriah torrado','Café Moriah torrado.',700,ARRAY[]::INTEGER[],90),
('menu-caf-010','MENU-CAF-010','Café da Manhã','Achocolatado','Achocolatado.',900,ARRAY[]::INTEGER[],100),
('menu-caf-011','MENU-CAF-011','Café da Manhã','Leite','Leite.',500,ARRAY[]::INTEGER[],110),
('menu-caf-012','MENU-CAF-012','Café da Manhã','Capuchino Moriah','Capuchino Moriah.',1000,ARRAY[]::INTEGER[],120),
('menu-dia-001','MENU-DIA-001','Prato do Dia','Carne de panela','Prato do dia de segunda-feira. Acompanha farofa, arroz, feijão, salada e refrigerante 269 ml.',3200,ARRAY[1]::INTEGER[],10),
('menu-dia-002','MENU-DIA-002','Prato do Dia','Virado à paulista','Prato do dia de terça-feira. Acompanha farofa, arroz, feijão, salada e refrigerante 269 ml.',2800,ARRAY[2]::INTEGER[],20),
('menu-dia-003','MENU-DIA-003','Prato do Dia','Feijoada','Prato do dia de quarta-feira. Acompanha farofa, arroz, feijão, salada e refrigerante 269 ml.',3500,ARRAY[3]::INTEGER[],30),
('menu-dia-004','MENU-DIA-004','Prato do Dia','Parmegiana de carne','Prato do dia de quinta-feira. Acompanha farofa, arroz, feijão, salada e refrigerante 269 ml.',3800,ARRAY[4]::INTEGER[],40),
('menu-dia-005','MENU-DIA-005','Prato do Dia','Costelinha suína','Prato do dia de sexta-feira. Acompanha farofa, arroz, feijão, salada e refrigerante 269 ml.',3300,ARRAY[5]::INTEGER[],50),
('menu-dia-006','MENU-DIA-006','Prato do Dia','Moqueca de peixe','Prato do dia de sábado. Acompanha farofa, arroz, feijão, salada e refrigerante 269 ml.',3500,ARRAY[6]::INTEGER[],60),
('menu-dia-007','MENU-DIA-007','Prato do Dia','Churrasco','Prato do dia de domingo. Acompanha farofa, arroz, feijão, salada e refrigerante 269 ml.',3400,ARRAY[0]::INTEGER[],70),
('menu-pra-001','MENU-PRA-001','Pratos','Calabresa acebolada','Acompanha farofa, arroz, feijão, salada e refrigerante 269 ml.',2800,ARRAY[]::INTEGER[],10),
('menu-pra-002','MENU-PRA-002','Pratos','Bife acebolado','Acompanha farofa, arroz, feijão, salada e refrigerante 269 ml.',3200,ARRAY[]::INTEGER[],20),
('menu-pra-003','MENU-PRA-003','Pratos','Omelete recheado','Acompanha farofa, arroz, feijão, salada e refrigerante 269 ml.',2300,ARRAY[]::INTEGER[],30),
('menu-pra-004','MENU-PRA-004','Pratos','Frango grelhado com fritas','Acompanha farofa, arroz, feijão, salada e refrigerante 269 ml.',2500,ARRAY[]::INTEGER[],40),
('menu-pra-005','MENU-PRA-005','Pratos','Frango a passarinho','Acompanha farofa, arroz, feijão, salada e refrigerante 269 ml.',2800,ARRAY[]::INTEGER[],50),
('menu-pra-006','MENU-PRA-006','Pratos','Filé de peixe à milanesa','Acompanha farofa, arroz, feijão, salada e refrigerante 269 ml.',3200,ARRAY[]::INTEGER[],60),
('menu-pra-007','MENU-PRA-007','Pratos','Macarronada à bolonhesa','Acompanha farofa, arroz, feijão, salada e refrigerante 269 ml.',2800,ARRAY[]::INTEGER[],70),
('menu-pra-008','MENU-PRA-008','Pratos','Panqueca (serve 2 pessoas)','Panqueca para duas pessoas com carne, queijo, frango e catupiry. Adicionais disponíveis.',5200,ARRAY[]::INTEGER[],80),
('menu-pra-009','MENU-PRA-009','Pratos','Prato kids com fritas','Escolha entre calabresa, iscas de carne, carne moída ou nuggets. Acompanha refrigerante 269 ml e sobremesa.',2200,ARRAY[]::INTEGER[],90),
('menu-por-001','MENU-POR-001','Porções','Isca de frango','Porção de iscas de frango.',3800,ARRAY[]::INTEGER[],10),
('menu-por-002','MENU-POR-002','Porções','Contra-filé acebolado','Porção de contra-filé acebolado.',4200,ARRAY[]::INTEGER[],20),
('menu-por-003','MENU-POR-003','Porções','Tilápia com anéis de cebola','Porção de tilápia com anéis de cebola.',4500,ARRAY[]::INTEGER[],30),
('menu-por-004','MENU-POR-004','Porções','Anéis de cebola e cebola crispy','Porção de anéis de cebola e cebola crispy.',3800,ARRAY[]::INTEGER[],40),
('menu-por-005','MENU-POR-005','Porções','Fritas recheadas','Porção de fritas recheadas.',3500,ARRAY[]::INTEGER[],50),
('menu-por-006','MENU-POR-006','Porções','Fritas simples','Porção de fritas simples.',2800,ARRAY[]::INTEGER[],60),
('menu-por-007','MENU-POR-007','Porções','Pastel','Escolha o recheio: frango com catupiry, 3 queijos, queijo, carne, palmito ou alho.',1400,ARRAY[]::INTEGER[],70),
('menu-por-008','MENU-POR-008','Porções','Pastel Big Monster Especial','Pastel especial com todos os recheios.',2200,ARRAY[]::INTEGER[],80),
('menu-por-009','MENU-POR-009','Porções','6 mini pastéis','Seis mini pastéis nos sabores carne, queijo e frango.',2400,ARRAY[]::INTEGER[],90),
('menu-por-010','MENU-POR-010','Porções','Caldos','Escolha o sabor: calabresa, frango, carne, caldo verde, caldo de moqueca ou legumes.',2600,ARRAY[]::INTEGER[],100),
('menu-pan-s-001','MENU-PAN-S-001','Panquecas Salgadas','Panqueca de frango','Panqueca salgada de frango.',2400,ARRAY[]::INTEGER[],10),
('menu-pan-s-002','MENU-PAN-S-002','Panquecas Salgadas','Panqueca de carne','Panqueca salgada de carne.',2400,ARRAY[]::INTEGER[],20),
('menu-pan-s-003','MENU-PAN-S-003','Panquecas Salgadas','Panqueca de calabresa','Panqueca salgada de calabresa.',2400,ARRAY[]::INTEGER[],30),
('menu-pan-s-004','MENU-PAN-S-004','Panquecas Salgadas','Panqueca de presunto e queijo','Panqueca salgada de presunto e queijo.',2300,ARRAY[]::INTEGER[],40),
('menu-pan-s-005','MENU-PAN-S-005','Panquecas Salgadas','Panqueca de toscana com bacon','Panqueca salgada de toscana com bacon.',2500,ARRAY[]::INTEGER[],50),
('menu-pan-s-006','MENU-PAN-S-006','Panquecas Salgadas','Panqueca de costelinha','Panqueca salgada de costelinha.',2700,ARRAY[]::INTEGER[],60),
('menu-pan-s-007','MENU-PAN-S-007','Panquecas Salgadas','Panqueca vegetariana','Opções vegetarianas: milho, espinafre, escarola, brócolis ou alho frito.',2200,ARRAY[]::INTEGER[],70),
('menu-pan-d-001','MENU-PAN-D-001','Panquecas Doces','Panqueca de doce de leite','Panqueca doce de doce de leite.',1800,ARRAY[]::INTEGER[],10),
('menu-pan-d-002','MENU-PAN-D-002','Panquecas Doces','Panqueca de brigadeiro','Panqueca doce de brigadeiro.',1800,ARRAY[]::INTEGER[],20),
('menu-pan-d-003','MENU-PAN-D-003','Panquecas Doces','Panqueca de Nutella','Panqueca doce de Nutella.',1800,ARRAY[]::INTEGER[],30),
('menu-pan-d-004','MENU-PAN-D-004','Panquecas Doces','Panqueca de beijinho','Panqueca doce de beijinho.',1800,ARRAY[]::INTEGER[],40),
('menu-pan-d-005','MENU-PAN-D-005','Panquecas Doces','Panqueca de Sonho de Valsa','Panqueca doce de Sonho de Valsa.',1900,ARRAY[]::INTEGER[],50),
('menu-pan-d-006','MENU-PAN-D-006','Panquecas Doces','Panqueca de morango com leite condensado','Panqueca doce de morango com leite condensado.',2000,ARRAY[]::INTEGER[],60),
('menu-pan-d-007','MENU-PAN-D-007','Panquecas Doces','Panqueca de abacaxi com chocolate','Panqueca doce de abacaxi com chocolate.',2000,ARRAY[]::INTEGER[],70),
('menu-pan-d-008','MENU-PAN-D-008','Panquecas Doces','Panqueca de banana com canela','Panqueca doce de banana com canela.',1800,ARRAY[]::INTEGER[],80)),
resolved AS (
 SELECT i.*,c."id" AS "categoryId" FROM incoming i
 JOIN LATERAL (SELECT c0."id" FROM "RestaurantCategory" c0 WHERE lower(c0."name")=lower(i."categoryName") ORDER BY CASE WHEN c0."id" LIKE 'menu-cat-%' THEN 0 ELSE 1 END,c0."sortOrder",c0."id" LIMIT 1)c ON true
)
INSERT INTO "RestaurantProduct" ("id","categoryId","name","description","priceCents","sku","active","featured","soldOut","sortOrder","allowNotes","availableDays","trackStock","stockQty","minStockQty","updatedAt")
SELECT r."id",r."categoryId",r."name",r."description",r."priceCents",r."sku",true,false,false,r."sortOrder",true,r."availableDays",false,0,0,CURRENT_TIMESTAMP
FROM resolved r WHERE NOT EXISTS(SELECT 1 FROM "RestaurantProduct" p WHERE p."sku"=r."sku" OR lower(p."name")=lower(r."name"))
ON CONFLICT("sku") DO NOTHING;

WITH incoming("id","name","required","minSelect","maxSelect") AS (VALUES ('menu-mod-suco','Sabores de suco natural',true,1,1),
('menu-mod-vitamina','Sabores de vitamina',true,1,1),
('menu-mod-vit-extra','Adicionais para vitamina',false,0,3),
('menu-mod-tapioca','Recheio da tapioca',true,1,1),
('menu-mod-refri269','Refrigerante 269 ml',true,1,1),
('menu-mod-pan2-extra','Adicionais da panqueca para 2',false,0,7),
('menu-mod-kids','Escolha do prato kids',true,1,1),
('menu-mod-pastel','Recheio do pastel',true,1,1),
('menu-mod-caldo','Sabor do caldo',true,1,1),
('menu-mod-pan-s-extra','Acréscimos das panquecas salgadas',false,0,6),
('menu-mod-pan-veg','Sabor da panqueca vegetariana',true,1,1))
UPDATE "RestaurantModifierGroup" g SET "required"=i."required","minSelect"=i."minSelect","maxSelect"=i."maxSelect","active"=true FROM incoming i WHERE lower(g."name")=lower(i."name");
WITH incoming("id","name","required","minSelect","maxSelect") AS (VALUES ('menu-mod-suco','Sabores de suco natural',true,1,1),
('menu-mod-vitamina','Sabores de vitamina',true,1,1),
('menu-mod-vit-extra','Adicionais para vitamina',false,0,3),
('menu-mod-tapioca','Recheio da tapioca',true,1,1),
('menu-mod-refri269','Refrigerante 269 ml',true,1,1),
('menu-mod-pan2-extra','Adicionais da panqueca para 2',false,0,7),
('menu-mod-kids','Escolha do prato kids',true,1,1),
('menu-mod-pastel','Recheio do pastel',true,1,1),
('menu-mod-caldo','Sabor do caldo',true,1,1),
('menu-mod-pan-s-extra','Acréscimos das panquecas salgadas',false,0,6),
('menu-mod-pan-veg','Sabor da panqueca vegetariana',true,1,1))
INSERT INTO "RestaurantModifierGroup" ("id","name","required","minSelect","maxSelect","active")
SELECT i."id",i."name",i."required",i."minSelect",i."maxSelect",true FROM incoming i
WHERE NOT EXISTS(SELECT 1 FROM "RestaurantModifierGroup" g WHERE lower(g."name")=lower(i."name"));

WITH incoming("id","groupName","name","priceCents") AS (VALUES ('menu-opt-001','Sabores de suco natural','Laranja',0),
('menu-opt-002','Sabores de suco natural','Limão',0),
('menu-opt-003','Sabores de suco natural','Abacaxi',0),
('menu-opt-004','Sabores de suco natural','Morango',0),
('menu-opt-005','Sabores de suco natural','Maracujá',0),
('menu-opt-006','Sabores de vitamina','Banana',0),
('menu-opt-007','Sabores de vitamina','Abacate',0),
('menu-opt-008','Sabores de vitamina','Mamão',0),
('menu-opt-009','Sabores de vitamina','Mista',0),
('menu-opt-010','Adicionais para vitamina','Aveia',300),
('menu-opt-011','Adicionais para vitamina','Cereais',300),
('menu-opt-012','Adicionais para vitamina','Leite em pó',300),
('menu-opt-013','Recheio da tapioca','Carne seca',0),
('menu-opt-014','Recheio da tapioca','Manteiga do Nordeste',0),
('menu-opt-015','Recheio da tapioca','Ovos mexidos',0),
('menu-opt-016','Refrigerante 269 ml','Coca-Cola 269 ml',0),
('menu-opt-017','Refrigerante 269 ml','Guaraná Antarctica 269 ml',0),
('menu-opt-018','Adicionais da panqueca para 2','Bacon',700),
('menu-opt-019','Adicionais da panqueca para 2','Milho',700),
('menu-opt-020','Adicionais da panqueca para 2','Pimenta',700),
('menu-opt-021','Adicionais da panqueca para 2','Muçarela',700),
('menu-opt-022','Adicionais da panqueca para 2','Cheddar',700),
('menu-opt-023','Adicionais da panqueca para 2','Calabresa',700),
('menu-opt-024','Adicionais da panqueca para 2','Palmito',700),
('menu-opt-025','Escolha do prato kids','Calabresa',0),
('menu-opt-026','Escolha do prato kids','Iscas de carne',0),
('menu-opt-027','Escolha do prato kids','Carne moída',0),
('menu-opt-028','Escolha do prato kids','Nuggets',0),
('menu-opt-029','Recheio do pastel','Frango com catupiry',0),
('menu-opt-030','Recheio do pastel','3 queijos',0),
('menu-opt-031','Recheio do pastel','Queijo',0),
('menu-opt-032','Recheio do pastel','Carne',0),
('menu-opt-033','Recheio do pastel','Palmito',0),
('menu-opt-034','Recheio do pastel','Alho',0),
('menu-opt-035','Sabor do caldo','Calabresa',0),
('menu-opt-036','Sabor do caldo','Frango',0),
('menu-opt-037','Sabor do caldo','Carne',0),
('menu-opt-038','Sabor do caldo','Caldo verde',0),
('menu-opt-039','Sabor do caldo','Caldo de moqueca',0),
('menu-opt-040','Sabor do caldo','Legumes',0),
('menu-opt-041','Acréscimos das panquecas salgadas','Bacon',500),
('menu-opt-042','Acréscimos das panquecas salgadas','Catupiry',500),
('menu-opt-043','Acréscimos das panquecas salgadas','Cheddar',500),
('menu-opt-044','Acréscimos das panquecas salgadas','3 queijos',600),
('menu-opt-045','Acréscimos das panquecas salgadas','Queijo',400),
('menu-opt-046','Acréscimos das panquecas salgadas','Alho frito',400),
('menu-opt-047','Sabor da panqueca vegetariana','Milho',0),
('menu-opt-048','Sabor da panqueca vegetariana','Espinafre',0),
('menu-opt-049','Sabor da panqueca vegetariana','Escarola',0),
('menu-opt-050','Sabor da panqueca vegetariana','Brócolis',0),
('menu-opt-051','Sabor da panqueca vegetariana','Alho frito',0)),
resolved AS (
 SELECT i.*,g."id" AS "groupId" FROM incoming i
 JOIN LATERAL (SELECT g0."id" FROM "RestaurantModifierGroup" g0 WHERE lower(g0."name")=lower(i."groupName") ORDER BY CASE WHEN g0."id" LIKE 'menu-mod-%' THEN 0 ELSE 1 END,g0."id" LIMIT 1)g ON true
)
UPDATE "RestaurantModifierOption" o SET "priceCents"=r."priceCents","active"=true FROM resolved r
WHERE o."groupId"=r."groupId" AND lower(o."name")=lower(r."name");

WITH incoming("id","groupName","name","priceCents") AS (VALUES ('menu-opt-001','Sabores de suco natural','Laranja',0),
('menu-opt-002','Sabores de suco natural','Limão',0),
('menu-opt-003','Sabores de suco natural','Abacaxi',0),
('menu-opt-004','Sabores de suco natural','Morango',0),
('menu-opt-005','Sabores de suco natural','Maracujá',0),
('menu-opt-006','Sabores de vitamina','Banana',0),
('menu-opt-007','Sabores de vitamina','Abacate',0),
('menu-opt-008','Sabores de vitamina','Mamão',0),
('menu-opt-009','Sabores de vitamina','Mista',0),
('menu-opt-010','Adicionais para vitamina','Aveia',300),
('menu-opt-011','Adicionais para vitamina','Cereais',300),
('menu-opt-012','Adicionais para vitamina','Leite em pó',300),
('menu-opt-013','Recheio da tapioca','Carne seca',0),
('menu-opt-014','Recheio da tapioca','Manteiga do Nordeste',0),
('menu-opt-015','Recheio da tapioca','Ovos mexidos',0),
('menu-opt-016','Refrigerante 269 ml','Coca-Cola 269 ml',0),
('menu-opt-017','Refrigerante 269 ml','Guaraná Antarctica 269 ml',0),
('menu-opt-018','Adicionais da panqueca para 2','Bacon',700),
('menu-opt-019','Adicionais da panqueca para 2','Milho',700),
('menu-opt-020','Adicionais da panqueca para 2','Pimenta',700),
('menu-opt-021','Adicionais da panqueca para 2','Muçarela',700),
('menu-opt-022','Adicionais da panqueca para 2','Cheddar',700),
('menu-opt-023','Adicionais da panqueca para 2','Calabresa',700),
('menu-opt-024','Adicionais da panqueca para 2','Palmito',700),
('menu-opt-025','Escolha do prato kids','Calabresa',0),
('menu-opt-026','Escolha do prato kids','Iscas de carne',0),
('menu-opt-027','Escolha do prato kids','Carne moída',0),
('menu-opt-028','Escolha do prato kids','Nuggets',0),
('menu-opt-029','Recheio do pastel','Frango com catupiry',0),
('menu-opt-030','Recheio do pastel','3 queijos',0),
('menu-opt-031','Recheio do pastel','Queijo',0),
('menu-opt-032','Recheio do pastel','Carne',0),
('menu-opt-033','Recheio do pastel','Palmito',0),
('menu-opt-034','Recheio do pastel','Alho',0),
('menu-opt-035','Sabor do caldo','Calabresa',0),
('menu-opt-036','Sabor do caldo','Frango',0),
('menu-opt-037','Sabor do caldo','Carne',0),
('menu-opt-038','Sabor do caldo','Caldo verde',0),
('menu-opt-039','Sabor do caldo','Caldo de moqueca',0),
('menu-opt-040','Sabor do caldo','Legumes',0),
('menu-opt-041','Acréscimos das panquecas salgadas','Bacon',500),
('menu-opt-042','Acréscimos das panquecas salgadas','Catupiry',500),
('menu-opt-043','Acréscimos das panquecas salgadas','Cheddar',500),
('menu-opt-044','Acréscimos das panquecas salgadas','3 queijos',600),
('menu-opt-045','Acréscimos das panquecas salgadas','Queijo',400),
('menu-opt-046','Acréscimos das panquecas salgadas','Alho frito',400),
('menu-opt-047','Sabor da panqueca vegetariana','Milho',0),
('menu-opt-048','Sabor da panqueca vegetariana','Espinafre',0),
('menu-opt-049','Sabor da panqueca vegetariana','Escarola',0),
('menu-opt-050','Sabor da panqueca vegetariana','Brócolis',0),
('menu-opt-051','Sabor da panqueca vegetariana','Alho frito',0)),
resolved AS (
 SELECT i.*,g."id" AS "groupId" FROM incoming i
 JOIN LATERAL (SELECT g0."id" FROM "RestaurantModifierGroup" g0 WHERE lower(g0."name")=lower(i."groupName") ORDER BY CASE WHEN g0."id" LIKE 'menu-mod-%' THEN 0 ELSE 1 END,g0."id" LIMIT 1)g ON true
)
INSERT INTO "RestaurantModifierOption" ("id","groupId","name","priceCents","active")
SELECT r."id",r."groupId",r."name",r."priceCents",true FROM resolved r
WHERE NOT EXISTS(SELECT 1 FROM "RestaurantModifierOption" o WHERE o."groupId"=r."groupId" AND lower(o."name")=lower(r."name"));

WITH links("productName","groupName") AS (VALUES ('Suco natural 500 ml','Sabores de suco natural'),
('Vitamina 500 ml','Sabores de vitamina'),
('Vitamina 500 ml','Adicionais para vitamina'),
('Tapioca','Recheio da tapioca'),
('Carne de panela','Refrigerante 269 ml'),
('Virado à paulista','Refrigerante 269 ml'),
('Feijoada','Refrigerante 269 ml'),
('Parmegiana de carne','Refrigerante 269 ml'),
('Costelinha suína','Refrigerante 269 ml'),
('Moqueca de peixe','Refrigerante 269 ml'),
('Churrasco','Refrigerante 269 ml'),
('Calabresa acebolada','Refrigerante 269 ml'),
('Bife acebolado','Refrigerante 269 ml'),
('Omelete recheado','Refrigerante 269 ml'),
('Frango grelhado com fritas','Refrigerante 269 ml'),
('Frango a passarinho','Refrigerante 269 ml'),
('Filé de peixe à milanesa','Refrigerante 269 ml'),
('Macarronada à bolonhesa','Refrigerante 269 ml'),
('Panqueca (serve 2 pessoas)','Refrigerante 269 ml'),
('Prato kids com fritas','Refrigerante 269 ml'),
('Panqueca (serve 2 pessoas)','Adicionais da panqueca para 2'),
('Prato kids com fritas','Escolha do prato kids'),
('Pastel','Recheio do pastel'),
('Caldos','Sabor do caldo'),
('Panqueca de frango','Acréscimos das panquecas salgadas'),
('Panqueca de carne','Acréscimos das panquecas salgadas'),
('Panqueca de calabresa','Acréscimos das panquecas salgadas'),
('Panqueca de presunto e queijo','Acréscimos das panquecas salgadas'),
('Panqueca de toscana com bacon','Acréscimos das panquecas salgadas'),
('Panqueca de costelinha','Acréscimos das panquecas salgadas'),
('Panqueca vegetariana','Acréscimos das panquecas salgadas'),
('Panqueca vegetariana','Sabor da panqueca vegetariana')),
resolved AS (
 SELECT p."id" AS "productId",g."id" AS "groupId" FROM links l
 JOIN LATERAL (SELECT p0."id" FROM "RestaurantProduct" p0 WHERE lower(p0."name")=lower(l."productName") ORDER BY CASE WHEN p0."sku" LIKE 'MENU-%' THEN 0 ELSE 1 END,p0."id" LIMIT 1)p ON true
 JOIN LATERAL (SELECT g0."id" FROM "RestaurantModifierGroup" g0 WHERE lower(g0."name")=lower(l."groupName") ORDER BY CASE WHEN g0."id" LIKE 'menu-mod-%' THEN 0 ELSE 1 END,g0."id" LIMIT 1)g ON true
)
INSERT INTO "RestaurantProductModifierGroup" ("productId","groupId")
SELECT "productId","groupId" FROM resolved ON CONFLICT("productId","groupId") DO NOTHING;
COMMIT;
