-- Initial Moriah CMS production schema
CREATE TABLE "SiteSettings" ("id" TEXT NOT NULL DEFAULT 'main',"siteName" TEXT NOT NULL DEFAULT 'Pousada Moriah',"tagline" TEXT NOT NULL DEFAULT 'Seu lugar perto de tudo. Do seu jeito.',"whatsapp" TEXT,"instagram" TEXT,"address" TEXT,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "SiteSettings_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Accommodation" ("id" TEXT NOT NULL,"name" TEXT NOT NULL,"description" TEXT NOT NULL,"type" TEXT NOT NULL,"priceCents" INTEGER,"capacity" INTEGER NOT NULL DEFAULT 2,"active" BOOLEAN NOT NULL DEFAULT true,"featured" BOOLEAN NOT NULL DEFAULT false,"coverImage" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "Accommodation_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Promotion" ("id" TEXT NOT NULL,"title" TEXT NOT NULL,"description" TEXT,"coupon" TEXT,"startsAt" TIMESTAMP(3),"endsAt" TIMESTAMP(3),"active" BOOLEAN NOT NULL DEFAULT true,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "Promotion_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Media" ("id" TEXT NOT NULL,"url" TEXT NOT NULL,"alt" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "Media_pkey" PRIMARY KEY ("id"));
CREATE TABLE "BookingLead" ("id" TEXT NOT NULL,"name" TEXT NOT NULL,"email" TEXT,"phone" TEXT NOT NULL,"checkIn" TIMESTAMP(3),"checkOut" TIMESTAMP(3),"guests" INTEGER NOT NULL DEFAULT 1,"message" TEXT,"status" TEXT NOT NULL DEFAULT 'NEW',"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "BookingLead_pkey" PRIMARY KEY ("id"));
CREATE TABLE "IntegrationSettings" ("id" TEXT NOT NULL DEFAULT 'main',"firebaseApiKey" TEXT,"firebaseAuthDomain" TEXT,"firebaseProjectId" TEXT,"firebaseStorageBucket" TEXT,"firebaseMessagingSenderId" TEXT,"firebaseAppId" TEXT,"firebaseVapidKey" TEXT,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "IntegrationSettings_pkey" PRIMARY KEY ("id"));
CREATE TABLE "BlogPost" ("id" TEXT NOT NULL,"title" TEXT NOT NULL,"slug" TEXT NOT NULL,"excerpt" TEXT,"content" TEXT NOT NULL,"coverImage" TEXT,"published" BOOLEAN NOT NULL DEFAULT false,"publishedAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "BlogPost_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ChannelIntegration" ("id" TEXT NOT NULL,"provider" TEXT NOT NULL,"name" TEXT NOT NULL,"importUrl" TEXT,"exportToken" TEXT,"active" BOOLEAN NOT NULL DEFAULT true,"lastSyncAt" TIMESTAMP(3),"lastError" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "ChannelIntegration_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ChannelBlock" ("id" TEXT NOT NULL,"integrationId" TEXT NOT NULL,"externalUid" TEXT NOT NULL,"summary" TEXT,"startsAt" TIMESTAMP(3) NOT NULL,"endsAt" TIMESTAMP(3) NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "ChannelBlock_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "BlogPost_slug_key" ON "BlogPost"("slug");
CREATE UNIQUE INDEX "ChannelIntegration_exportToken_key" ON "ChannelIntegration"("exportToken");
CREATE UNIQUE INDEX "ChannelBlock_integrationId_externalUid_key" ON "ChannelBlock"("integrationId","externalUid");
CREATE INDEX "ChannelBlock_startsAt_endsAt_idx" ON "ChannelBlock"("startsAt","endsAt");
