"use server";import {prisma} from "../../lib/prisma";import {revalidatePath} from "next/cache";
export async function createAccommodation(formData:FormData){const name=String(formData.get("name")||"").trim();const description=String(formData.get("description")||"").trim();const type=String(formData.get("type")||"POUSADA");const capacity=Math.max(1,Number(formData.get("capacity")||1));if(!name||!description)throw new Error("Nome e descrição são obrigatórios.");await prisma.accommodation.create({data:{name,description,type,capacity,active:true}});revalidatePath("/admin/hospedagens");revalidatePath("/");}
export async function createPromotion(formData:FormData){const title=String(formData.get("title")||"").trim();const description=String(formData.get("description")||"").trim();const coupon=String(formData.get("coupon")||"").trim()||null;if(!title)throw new Error("Título obrigatório.");await prisma.promotion.create({data:{title,description:description||null,coupon,active:true}});revalidatePath("/admin/promocoes");revalidatePath("/");}
export async function saveSettings(formData:FormData){await prisma.siteSettings.upsert({where:{id:"main"},create:{id:"main",siteName:String(formData.get("siteName")||"Pousada Moriah"),tagline:String(formData.get("tagline")||""),whatsapp:String(formData.get("whatsapp")||"")||null,instagram:String(formData.get("instagram")||"")||null,address:String(formData.get("address")||"")||null},update:{siteName:String(formData.get("siteName")||"Pousada Moriah"),tagline:String(formData.get("tagline")||""),whatsapp:String(formData.get("whatsapp")||"")||null,instagram:String(formData.get("instagram")||"")||null,address:String(formData.get("address")||"")||null}});revalidatePath("/admin/configuracoes");revalidatePath("/");}
export async function createBookingLead(formData:FormData){const name=String(formData.get("name")||"").trim();const phone=String(formData.get("phone")||"").trim();if(!name||!phone)throw new Error("Nome e WhatsApp são obrigatórios.");const checkIn=String(formData.get("checkIn")||"");const checkOut=String(formData.get("checkOut")||"");await prisma.bookingLead.create({data:{name,phone,email:String(formData.get("email")||"").trim()||null,checkIn:checkIn?new Date(checkIn+"T12:00:00"):null,checkOut:checkOut?new Date(checkOut+"T12:00:00"):null,guests:Math.max(1,Number(formData.get("guests")||1)),message:String(formData.get("message")||"").trim()||null,status:"NEW"}});revalidatePath("/admin/reservas");}
export async function setBookingStatus(formData:FormData){const id=String(formData.get("id")||"");const status=String(formData.get("status")||"");if(id&&["NEW","CONTACTED","CONFIRMED","CANCELLED"].includes(status)){await prisma.bookingLead.update({where:{id},data:{status}});revalidatePath("/admin/reservas");}}

export async function toggleAccommodation(formData:FormData){const id=String(formData.get("id")||"");const item=await prisma.accommodation.findUnique({where:{id}});if(item){await prisma.accommodation.update({where:{id},data:{active:!item.active}});revalidatePath("/admin/hospedagens");revalidatePath("/");}}
export async function deleteAccommodation(formData:FormData){const id=String(formData.get("id")||"");if(id){await prisma.accommodation.delete({where:{id}});revalidatePath("/admin/hospedagens");revalidatePath("/");}}

export async function updateAccommodation(formData:FormData){const id=String(formData.get("id")||"");const name=String(formData.get("name")||"").trim();const description=String(formData.get("description")||"").trim();const type=String(formData.get("type")||"POUSADA");const capacity=Math.max(1,Number(formData.get("capacity")||1));const rawPrice=String(formData.get("price")||"").replace(",",".");const priceCents=rawPrice?Math.max(0,Math.round(Number(rawPrice)*100)):null;const coverImage=String(formData.get("coverImage")||"").trim()||null;const featured=formData.get("featured")==="on";if(!id||!name||!description)throw new Error("Dados obrigatórios ausentes.");await prisma.accommodation.update({where:{id},data:{name,description,type,capacity,priceCents,coverImage,featured}});revalidatePath("/admin/hospedagens");revalidatePath("/");}
export async function addMedia(formData:FormData){const url=String(formData.get("url")||"").trim();const alt=String(formData.get("alt")||"").trim()||null;if(!url)throw new Error("URL da imagem obrigatória.");await prisma.media.create({data:{url,alt}});revalidatePath("/admin/galeria");}
export async function deleteMedia(formData:FormData){const id=String(formData.get("id")||"");if(id){await prisma.media.delete({where:{id}});revalidatePath("/admin/galeria");}}
