ALTER TABLE "RestaurantOrder"
  ADD COLUMN IF NOT EXISTS "preparingAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "readyAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "deliveredAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "cancelledAt" TIMESTAMP(3);

ALTER TABLE "RestaurantSettings"
  ADD COLUMN IF NOT EXISTS "prepTargetMinutes" INTEGER NOT NULL DEFAULT 25,
  ADD COLUMN IF NOT EXISTS "kdsSoundEnabled" BOOLEAN NOT NULL DEFAULT true;
