"use server";
import {Prisma} from "@prisma/client";import {revalidatePath} from "next/cache";import {redirect} from "next/navigation";import {prisma} from "../../../lib/prisma";import {requireAdmin} from "../../../lib/admin-auth";
const tx=(f:FormData,n:string,m:number)=>String(f.get(n)||"").trim().slice(0,m);
const slugify=(v:string)=>v.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"").slice(0,90);
function color(f:FormData,n:string,d:string){const v=tx(f,n,7);return /^#[0-9a-f]{6}$/i.test(v)?v.toUpperCase():d}
function dt(f:FormData,n:string,req=false){const v=tx(f,n,40);if(!v){if(req)throw new Error("Preencha a data do evento.");return null}const norm=/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}$/.test(v)?v+":00-03:00":v;const d=new Date(norm);if(Number.isNaN(d.getTime()))throw new Error("Data inválida.");return d}
function href(v:string){if(!v)return null;if(v.startsWith("/")&&!v.startsWith("//"))return v;const u=new URL(v);if(u.protocol!=="https:")throw new Error("O link externo deve usar HTTPS.");return u.toString()}
function ints(f:FormData,n:string,d:number){const r=tx(f,n,20);const v=r===""?d:Number(r);if(!Number.isInteger(v)||v<0)throw new Error("Ordem inválida.");return v}
const gallery=(f:FormData)=>[...new Set(f.getAll("galleryImages").map(v=>String(v).trim()).filter(Boolean))].slice(0,20);
async function audit(userId:string,action:string,id:string,details:Prisma.InputJsonObject){await prisma.adminAuditLog.create({data:{actorId:userId,action,targetType:"EVENT",targetId:id,details}})}
function data(f:FormData){const title=tx(f,"title",140);if(!title)throw new Error("Título obrigatório.");const startsAt=dt(f,"startsAt",true)!;const endsAt=dt(f,"endsAt");if(endsAt&&endsAt<=startsAt)throw new Error("Encerramento inválido.");const r1=dt(f,"rouletteThemeStartsAt"),r2=dt(f,"rouletteThemeEndsAt");if(r1&&r2&&r2<=r1)throw new Error("Janela visual inválida.");return {slug:slugify(tx(f,"slug",100))||slugify(title),title,eyebrow:tx(f,"eyebrow",100)||null,summary:tx(f,"summary",400)||null,description:tx(f,"description",12000),category:tx(f,"category",80)||"EVENTO",venue:tx(f,"venue",160)||null,address:tx(f,"address",300)||null,startsAt,endsAt,coverImage:tx(f,"coverImage",1000)||null,galleryImages:gallery(f),badge:tx(f,"badge",80)||null,ctaLabel:tx(f,"ctaLabel",100)||null,ctaHref:href(tx(f,"ctaHref",500)),priceLabel:tx(f,"priceLabel",100)||null,featured:f.get("featured")==="on",published:f.get("published")==="on",showOnHome:f.get("showOnHome")==="on",sortOrder:ints(f,"sortOrder",100),themePreset:tx(f,"themePreset",40)||"CELEBRATION",themePrimaryColor:color(f,"themePrimaryColor","#0B607A"),themeSecondaryColor:color(f,"themeSecondaryColor","#073B4C"),themeAccentColor:color(f,"themeAccentColor","#FFC845"),themeBackgroundColor:color(f,"themeBackgroundColor","#081F29"),themeTextColor:color(f,"themeTextColor","#FFFFFF"),rouletteThemeEnabled:f.get("rouletteThemeEnabled")==="on",rouletteThemeStartsAt:r1,rouletteThemeEndsAt:r2,rouletteBackgroundImage:tx(f,"rouletteBackgroundImage",1000)||null}}
export async function createEvent(f:FormData){const s=await requireAdmin();const d=data(f);const e=await prisma.moriahEvent.create({data:d});await audit(s.userId,"EVENT_CREATED",e.id,{title:e.title,slug:e.slug});revalidatePath("/");revalidatePath("/eventos");revalidatePath("/admin/eventos");revalidatePath("/et/roleta");redirect("/admin/eventos/"+e.id)}
export async function saveEvent(f:FormData){const s=await requireAdmin(),id=tx(f,"id",80),cur=await prisma.moriahEvent.findUnique({where:{id}});if(!cur)throw new Error("Evento não encontrado.");const d=data(f);await prisma.moriahEvent.update({where:{id},data:d});await audit(s.userId,"EVENT_UPDATED",id,{title:d.title,slug:d.slug,published:d.published});revalidatePath("/");revalidatePath("/eventos");revalidatePath("/eventos/"+cur.slug);revalidatePath("/eventos/"+d.slug);revalidatePath("/admin/eventos");revalidatePath("/admin/eventos/"+id);revalidatePath("/et/roleta")}
export async function deleteEvent(f:FormData){const s=await requireAdmin(),id=tx(f,"id",80),cur=await prisma.moriahEvent.findUnique({where:{id}});if(!cur)return;await audit(s.userId,"EVENT_DELETED",id,{title:cur.title,slug:cur.slug});await prisma.moriahEvent.delete({where:{id}});revalidatePath("/");revalidatePath("/eventos");revalidatePath("/admin/eventos");revalidatePath("/et/roleta");redirect("/admin/eventos")}
