import type {MoriahEvent} from "@prisma/client";import MediaPicker from "../components/media-picker";import MediaMultiPicker from "../components/media-multi-picker";
type M={id:string;url:string;alt:string|null};const local=(d:Date|null|undefined)=>d?new Date(d.getTime()-3*60*60_000).toISOString().slice(0,16):"";
export default function EventForm({action,event,media,submitLabel}:{action:(f:FormData)=>void|Promise<void>;event?:MoriahEvent|null;media:M[];submitLabel:string}){const v=event;return <form action={action} className="adminFormGrid">
{v&&<input type="hidden" name="id" value={v.id}/>}<label className="span2">Título<input name="title" required defaultValue={v?.title||""}/></label><label>Slug<input name="slug" defaultValue={v?.slug||""}/></label><label>Categoria<input name="category" defaultValue={v?.category||"EVENTO"}/></label><label>Chamada<input name="eyebrow" defaultValue={v?.eyebrow||""}/></label><label>Selo<input name="badge" defaultValue={v?.badge||""}/></label><label className="span2">Resumo<textarea name="summary" rows={3} defaultValue={v?.summary||""}/></label><label className="span2">Descrição completa<textarea name="description" rows={8} required defaultValue={v?.description||""}/></label>
<label>Início<input name="startsAt" type="datetime-local" required defaultValue={local(v?.startsAt)}/></label><label>Encerramento<input name="endsAt" type="datetime-local" defaultValue={local(v?.endsAt)}/></label><label>Local<input name="venue" defaultValue={v?.venue||""}/></label><label>Endereço<input name="address" defaultValue={v?.address||""}/></label><label>Preço / chamada<input name="priceLabel" defaultValue={v?.priceLabel||""}/></label><label>Ordem<input name="sortOrder" type="number" min="0" defaultValue={v?.sortOrder??100}/></label>
<div className="span2"><MediaPicker name="coverImage" media={media} defaultValue={v?.coverImage||""} label="Capa do evento" recommended="Horizontal • 1600 × 900 ou maior"/></div><div className="span2"><MediaMultiPicker name="galleryImages" media={media} defaultValues={v?.galleryImages||[]} label="Galeria do evento"/></div>
<label>Texto do botão<input name="ctaLabel" defaultValue={v?.ctaLabel||""}/></label><label>Destino do botão<input name="ctaHref" defaultValue={v?.ctaHref||""} placeholder="/reservar ou https://..."/></label>
<div className="span2 adminPageNote"><strong>Publicação</strong><div className="adminMetaRow"><label><input type="checkbox" name="published" defaultChecked={v?.published||false}/> Publicado</label><label><input type="checkbox" name="featured" defaultChecked={v?.featured||false}/> Destaque</label><label><input type="checkbox" name="showOnHome" defaultChecked={v?.showOnHome!==false}/> Mostrar na Home</label></div></div>
<div className="span2 adminPageNote"><strong>Identidade visual + Roleta 2.0</strong><p>O evento pode assumir automaticamente a aparência da roleta durante uma janela de datas.</p></div>
<label>Preset<select name="themePreset" defaultValue={v?.themePreset||"CELEBRATION"}><option value="CELEBRATION">Celebração</option><option value="SUMMER">Verão / Praia</option><option value="CHRISTMAS">Natal</option><option value="HALLOWEEN">Halloween</option><option value="ROMANCE">Romântico</option><option value="NEON">Neon / Festa</option><option value="ELEGANT">Elegante</option></select></label><label><input type="checkbox" name="rouletteThemeEnabled" defaultChecked={v?.rouletteThemeEnabled||false}/> Usar tema na roleta</label>
<label>Principal<input name="themePrimaryColor" type="color" defaultValue={v?.themePrimaryColor||"#0b607a"}/></label><label>Secundária<input name="themeSecondaryColor" type="color" defaultValue={v?.themeSecondaryColor||"#073b4c"}/></label><label>Destaque<input name="themeAccentColor" type="color" defaultValue={v?.themeAccentColor||"#ffc845"}/></label><label>Fundo<input name="themeBackgroundColor" type="color" defaultValue={v?.themeBackgroundColor||"#081f29"}/></label><label>Texto<input name="themeTextColor" type="color" defaultValue={v?.themeTextColor||"#ffffff"}/></label><label>Início tema<input name="rouletteThemeStartsAt" type="datetime-local" defaultValue={local(v?.rouletteThemeStartsAt)}/></label><label>Fim tema<input name="rouletteThemeEndsAt" type="datetime-local" defaultValue={local(v?.rouletteThemeEndsAt)}/></label>
<div className="span2"><MediaPicker name="rouletteBackgroundImage" media={media} defaultValue={v?.rouletteBackgroundImage||""} label="Fundo temático da roleta" recommended="Horizontal • alta resolução"/></div><button className="span2">{submitLabel}</button></form>}
