"use server";import {prisma} from "./prisma";import {requireAdmin} from "./admin-auth";import {revalidatePath} from "next/cache";
export async function createRestaurantCategory(formData:FormData){await requireAdmin();const name=String(formData.get("name")||"").trim();if(!name)throw new Error("Categoria obrigatória.");await prisma.restaurantCategory.create({data:{name}});revalidatePath("/admin/restaurante");}
export async function createRestaurantProduct(formData:FormData){await requireAdmin();const categoryId=String(formData.get("categoryId")||""),name=String(formData.get("name")||"").trim(),price=Number(String(formData.get("price")||"").replace(",",".")),cost=Number(String(formData.get("cost")||"").replace(",",".")),stock=Number(formData.get("stockQty")||0),min=Number(formData.get("minStockQty")||0);if(!categoryId||!name||!Number.isFinite(price)||price<0||!Number.isInteger(stock)||stock<0||!Number.isInteger(min)||min<0)throw new Error("Produto inválido.");await prisma.restaurantProduct.create({data:{categoryId,name,description:String(formData.get("description")||"").trim()||null,imageUrl:String(formData.get("imageUrl")||"").trim()||null,sku:String(formData.get("sku")||"").trim()||null,priceCents:Math.round(price*100),costCents:Number.isFinite(cost)&&cost>=0?Math.round(cost*100):null,stockQty:stock,minStockQty:min,trackStock:formData.get("trackStock")==="on"}});revalidatePath("/admin/restaurante");revalidatePath("/restaurante");}
export async function adjustRestaurantStock(formData:FormData){await requireAdmin();const productId=String(formData.get("productId")||""),quantity=Number(formData.get("quantity")||0),reason=String(formData.get("reason")||"Ajuste manual");if(!productId||!Number.isInteger(quantity)||quantity===0)throw new Error("Ajuste inválido.");await prisma.$transaction(async tx=>{const p=await tx.restaurantProduct.findUnique({where:{id:productId}});if(!p||p.stockQty+quantity<0)throw new Error("Estoque insuficiente.");await tx.restaurantProduct.update({where:{id:productId},data:{stockQty:{increment:quantity}}});await tx.restaurantStockMovement.create({data:{productId,type:quantity>0?"IN":"OUT",quantity,reason}})});revalidatePath("/admin/restaurante");revalidatePath("/restaurante");}
export async function setRestaurantOrderStatus(formData:FormData){await requireAdmin();const id=String(formData.get("id")||""),status=String(formData.get("status")||"");if(!["NEW","PREPARING","READY","DELIVERED","CANCELLED"].includes(status))throw new Error("Status inválido.");await prisma.restaurantOrder.update({where:{id},data:{status}});revalidatePath("/admin/restaurante/pedidos");}

export async function saveRestaurantSettings(formData:FormData){await requireAdmin();const openTime=String(formData.get("openTime")||"07:00"),closeTime=String(formData.get("closeTime")||"22:00");if(!/^\d{2}:\d{2}$/.test(openTime)||!/^\d{2}:\d{2}$/.test(closeTime))throw new Error("Horário inválido.");await prisma.restaurantSettings.upsert({where:{id:"main"},create:{id:"main",openTime,closeTime,acceptingOrders:formData.get("acceptingOrders")==="on",roomChargeEnabled:formData.get("roomChargeEnabled")==="on"},update:{openTime,closeTime,acceptingOrders:formData.get("acceptingOrders")==="on",roomChargeEnabled:formData.get("roomChargeEnabled")==="on"}});revalidatePath("/admin/restaurante");revalidatePath("/restaurante");}
export async function createIngredient(formData:FormData){await requireAdmin();const name=String(formData.get("name")||"").trim(),unit=String(formData.get("unit")||"un").trim(),stock=Number(formData.get("stockQty")||0),min=Number(formData.get("minStockQty")||0),cost=Number(String(formData.get("costPerUnit")||0).replace(",","."));if(!name||!unit||![stock,min,cost].every(Number.isFinite)||stock<0||min<0||cost<0)throw new Error("Insumo inválido.");await prisma.restaurantIngredient.create({data:{name,unit,stockQty:stock,minStockQty:min,costPerUnitCents:Math.round(cost*100)}});revalidatePath("/admin/restaurante/insumos");}
export async function adjustIngredientStock(formData:FormData){await requireAdmin();const ingredientId=String(formData.get("ingredientId")||""),q=Number(formData.get("quantity")||0),reason=String(formData.get("reason")||"Ajuste manual");if(!ingredientId||!Number.isFinite(q)||q===0)throw new Error("Ajuste inválido.");await prisma.$transaction(async tx=>{const i=await tx.restaurantIngredient.findUnique({where:{id:ingredientId}});if(!i||i.stockQty+q<0)throw new Error("Estoque de insumo insuficiente.");await tx.restaurantIngredient.update({where:{id:ingredientId},data:{stockQty:{increment:q}}});await tx.restaurantIngredientMovement.create({data:{ingredientId,type:q>0?"IN":"OUT",quantity:q,reason}})});revalidatePath("/admin/restaurante/insumos");}
export async function addRecipeItem(formData:FormData){await requireAdmin();const productId=String(formData.get("productId")||""),ingredientId=String(formData.get("ingredientId")||""),quantity=Number(formData.get("quantity")||0);if(!productId||!ingredientId||!Number.isFinite(quantity)||quantity<=0)throw new Error("Ficha técnica inválida.");await prisma.restaurantRecipeItem.upsert({where:{productId_ingredientId:{productId,ingredientId}},create:{productId,ingredientId,quantity},update:{quantity}});revalidatePath("/admin/restaurante/insumos");}
