ALTER TABLE "SitePage"
  ADD COLUMN IF NOT EXISTS "navLabel" TEXT,
  ADD COLUMN IF NOT EXISTS "showInNav" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "sortOrder" INTEGER NOT NULL DEFAULT 100;

ALTER TABLE "SiteSection"
  ADD COLUMN IF NOT EXISTS "videoUrl" TEXT,
  ADD COLUMN IF NOT EXISTS "anchorId" TEXT,
  ADD COLUMN IF NOT EXISTS "backgroundImageUrl" TEXT,
  ADD COLUMN IF NOT EXISTS "backgroundColor" TEXT,
  ADD COLUMN IF NOT EXISTS "textColor" TEXT,
  ADD COLUMN IF NOT EXISTS "animation" TEXT NOT NULL DEFAULT 'FADE_UP',
  ADD COLUMN IF NOT EXISTS "animationDelay" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "paddingY" INTEGER NOT NULL DEFAULT 96,
  ADD COLUMN IF NOT EXISTS "contentWidth" TEXT NOT NULL DEFAULT 'NORMAL',
  ADD COLUMN IF NOT EXISTS "hideMobile" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "hideDesktop" BOOLEAN NOT NULL DEFAULT false;

CREATE INDEX IF NOT EXISTS "SiteSection_anchorId_idx" ON "SiteSection"("anchorId");
CREATE INDEX IF NOT EXISTS "SitePage_showInNav_sortOrder_idx" ON "SitePage"("showInNav","sortOrder");
