ALTER TABLE "RouletteSettings"
ADD COLUMN "spectaclePreset" TEXT NOT NULL DEFAULT 'MAX',
ADD COLUMN "spinTurns" INTEGER NOT NULL DEFAULT 9,
ADD COLUMN "spinDurationMs" INTEGER NOT NULL DEFAULT 6200,
ADD COLUMN "idleMotionEnabled" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "chaseLightsEnabled" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "jackpotCrownEnabled" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "spinCalloutEnabled" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "winConfettiEnabled" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "spinButtonText" TEXT NOT NULL DEFAULT 'GIRAR AGORA!',
ADD COLUMN "spinCalloutText" TEXT NOT NULL DEFAULT 'APERTE O BOTAO E DESCUBRA SEU PREMIO';
