"use client";import type {CSSProperties,FormEvent} from "react";import {useRef,useState} from "react";import WheelCanvas,{WheelHandle,WheelSlice,WheelTheme} from "./wheel-canvas";import styles from "./roleta.module.css";
type S={title:string;subtitle:string;introText:string;googleReviewUrl:string|null;googleReviewLabel:string;termsText:string};type P=WheelSlice&{description:string|null};type T={preset:string;primary:string;secondary:string;accent:string;surface:string;text:string;background:string;backgroundImage:string|null;animationStyle:string;event:{title:string;badge:string|null;slug:string;startsAt:string}|null};
const amb=(a:string)=>a==="SNOW"?styles.ambientSnow:a==="BUBBLES"?styles.ambientBubbles:a==="SPARKLES"?styles.ambientSparkles:a==="NONE"?styles.ambientNone:styles.ambientConfetti;
export default function RouletteGame({settings,initialPrizes,theme}:{settings:S;initialPrizes:P[];theme:T}){const ref=useRef<WheelHandle>(null);const [step,setStep]=useState<"intro"|"identify"|"wheel"|"done">("intro"),[name,setName]=useState(""),[phone,setPhone]=useState(""),[consent,setConsent]=useState(false),[spinning,setSpinning]=useState(false),[error,setError]=useState(""),[slices,setSlices]=useState<WheelSlice[]>(initialPrizes),[result,setResult]=useState<{name:string;description:string|null;claimCode:string;expiresAt:string|null}|null>(null);
const vars={"--roulette-primary":theme.primary,"--roulette-secondary":theme.secondary,"--roulette-accent":theme.accent,"--roulette-surface":theme.surface,"--roulette-text":theme.text,"--roulette-bg":theme.background,"--roulette-image":theme.backgroundImage?`url("${theme.backgroundImage.replace(/"/g,"%22")}")`:"none"} as CSSProperties;const wt:WheelTheme={primary:theme.primary,secondary:theme.secondary,accent:theme.accent,surface:theme.surface};
function identify(e:FormEvent){e.preventDefault();setError("");if(name.trim().length<2)return setError("Informe seu nome.");if(phone.replace(/\D/g,"").length<10)return setError("Informe um telefone com DDD.");if(!consent)return setError("Aceite os termos para participar.");setStep("wheel")}
async function spin(){if(spinning)return;setSpinning(true);setError("");try{const r=await fetch("/api/etc/roleta/play",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name,phone,consent})}),d=await r.json();if(!r.ok)throw new Error(d.error||"Não foi possível girar.");setSlices(d.wheel);await ref.current?.spinTo(d.prize.id,d.wheel);setResult({name:d.prize.name,description:d.prize.description||null,claimCode:d.claimCode,expiresAt:d.expiresAt});setStep("done")}catch(e){setError(e instanceof Error?e.message:"Não foi possível girar.")}finally{setSpinning(false)}}
return <main className={styles.shell} style={vars}><div className={styles.backgroundImage}/><div className={styles.backgroundGlow}/><div className={styles.backgroundGrid}/><div className={styles.ambient+" "+amb(theme.animationStyle)}>{Array.from({length:26},(_,i)=><i key={i} style={{left:((i*37)%96+2)+"%",top:((i*53)%92+4)+"%",animationDelay:"-"+i*.31+"s",animationDuration:5+(i%5)+"s"}}/>)}</div>{step==="done"&&<div className={styles.winBurst}>{Array.from({length:38},(_,i)=><i key={i} style={{left:(i*29)%98+"%",animationDelay:(i%7)*.05+"s"}}/>)}</div>}
<section className={styles.card}><header className={styles.header}><div className={styles.headerGlow}/><span>MORIAH • ROLETA 2.0</span><h1>{settings.title}</h1><p>{settings.subtitle}</p>{theme.event&&<a className={styles.eventRibbon} href={"/eventos/"+theme.event.slug}><small>{theme.event.badge||"EVENTO ATIVO"}</small><b>{theme.event.title}</b><span>{new Date(theme.event.startsAt).toLocaleDateString("pt-BR",{day:"2-digit",month:"long"})} ↗</span></a>}</header>
{step==="intro"&&<div className={styles.intro}><div className={styles.stepBadge}>01 • EXPERIÊNCIA</div><h2>Quer contar como foi sua experiência?</h2><p>{settings.introText}</p>{settings.googleReviewUrl&&<a className={styles.googleButton} href={settings.googleReviewUrl} target="_blank" rel="noreferrer">{settings.googleReviewLabel} ↗</a>}<button className={styles.primary} onClick={()=>setStep("identify")}>Continuar para a roleta</button><small>A avaliação é opcional e não altera sua chance nem o prêmio.</small></div>}
{step==="identify"&&<form className={styles.form} onSubmit={identify}><div className={styles.stepBadge}>02 • IDENTIFICAÇÃO</div><h2>Quem vai tentar a sorte?</h2><label>Nome<input value={name} onChange={e=>setName(e.target.value)} required/></label><label>Telefone / WhatsApp<input value={phone} onChange={e=>setPhone(e.target.value)} inputMode="tel" required/></label><label className={styles.consent}><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>{settings.termsText}</span></label>{error&&<p className={styles.error}>{error}</p>}<button className={styles.primary}>Liberar minha roleta</button></form>}
{(step==="wheel"||step==="done")&&<div className={styles.game}><div className={styles.stepBadge}>{step==="done"?"04 • RESULTADO":"03 • ROLETA"}</div><div className={styles.wheelStage}><div className={styles.wheelHalo}/><WheelCanvas ref={ref} slices={slices} theme={wt}/></div>{step==="wheel"&&<>{error&&<p className={styles.error}>{error}</p>}<button className={styles.spinButton} onClick={spin} disabled={spinning||!slices.length}><span>{spinning?"Girando…":"GIRAR A ROLETA"}</span><i/></button><small>Resultado definido no servidor e registrado para auditoria.</small></>}{step==="done"&&result&&<div className={styles.result}><span>VOCÊ GANHOU</span><h2>{result.name}</h2>{result.description&&<p>{result.description}</p>}<div className={styles.claim}><small>CÓDIGO PARA RETIRADA</small><strong>{result.claimCode}</strong></div>{result.expiresAt&&<small>Válido até {new Date(result.expiresAt).toLocaleDateString("pt-BR")}.</small>}<p>Apresente este código à equipe da Moriah.</p></div>}</div>}</section></main>}
